name: Multi-OS Command

on: [push]

jobs:
  run-on-all:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Ejecutar comando en cada sistema operativo
        run: |
          echo "Running on ${{ matrix.os }}"
          uname -a || ver

